name: IAM user with GitHub action
env:
  Message: "Helo, i'm akash vaidya"

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

  workflow_dispatch:

jobs:
  my_terraform_job:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: "./main/practice"
    
      # - name: Terraform Init
      #   id: init
      #   run: |  
      #       rm -rf .terraform
      #       terraform init
      #       terraform init -reconfigure
      #   working-directory: "./main/practice"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: "./main/practice"

      - name: terraform destroy
        uses: dflook/terraform-destroy-workspace@v1
        with:
          path: terraform
          workspace: ${{ github.head_ref }}


      # - name: Terraform Plan
      #   if: github.event_name == 'push'
      #   id: pliam_useran
      #   run: terraform plan -no-color
      #   continue-on-error: true
      #   working-directory: "./main/practice"
      # - name: Terraform Apply
      #   # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: terraform apply -auto-approve
      #   working-directory: "./main/practice"
